[build]
  command = "npm run generate && npm run build"   # Commande pour construire le projet
  publish = "dist"            # Répertoire où les fichiers de build sont générés
  functions = "netlify/functions"  # Répertoire pour les fonctions serverless (si utilisé)

[functions]
  node_bundler = "esbuild"   # Utiliser esbuild pour les fonctions Netlify
